services:
  - type: web
    name: product-catalog-service
    repo: https://github.com/MariaaPcsa/spring-microservices-catalog-orders
    branch: main
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: catalog-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: catalog-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: catalog-db
          property: password
      - key: EUREKA_SERVER_URL
        value: https://seu-eureka-no-render.onrender.com/eureka
    autoDeploy: true

databases:
  - name: catalog-db
    plan: free
    databaseName: catalogdb
    user: cataloguser
