server:
  port: 8710

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-catalog
          uri: lb://product-catalog-service
          predicates:
            - Path=/produtos/**
        - id: order-simulator
          uri: lb://order-simulator-service
          predicates:
            - Path=/pedidos/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
