server:
  port: 8210

spring:
  application:
    name: order-simulator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Use service discovery from Gateway; but for direct local run we point to gateway base url
# When called via Gateway, the base url is still the catalog service logical name.
catalog:
  service:
    base-url: http://localhost:8710 # API Gateway base URL; Gateway will route /produtos to catalog

management:
  endpoints:
    web:
      exposure:
        include: health,info
